package ddl

import (
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/boringsql/dryrun/pkg/snapshot"
)

func sp(s string) *string { return &s }

func col(name, typ string) snapshot.Column {
	return snapshot.Column{Name: name, TypeName: typ, Nullable: true}
}

func tbl(name string, cols ...snapshot.Column) *snapshot.Table {
	return &snapshot.Table{Schema: "public", Name: name, Columns: cols}
}

func render(t *testing.T, snap *snapshot.SchemaSnapshot, tab *snapshot.Table) *Result {
	t.Helper()
	r, err := RenderTable(snap, tab)
	if err != nil {
		t.Fatalf("RenderTable: %v", err)
	}
	return r
}

func TestRenderColumns(t *testing.T) {
	notNull := func(c snapshot.Column) snapshot.Column { c.Nullable = false; return c }

	tests := []struct {
		name string
		col  snapshot.Column
		want string
	}{
		{"plain", col("a", "integer"), "a integer"},
		{"not null", notNull(col("a", "integer")), "a integer NOT NULL"},
		{"default", func() snapshot.Column { c := col("a", "integer"); c.Default = sp("42"); return c }(), "a integer DEFAULT 42"},
		{"identity always", func() snapshot.Column {
			c := notNull(col("id", "bigint"))
			c.Identity = sp("always")
			return c
		}(), "id bigint GENERATED ALWAYS AS IDENTITY NOT NULL"},
		{"identity by default", func() snapshot.Column {
			c := notNull(col("id", "bigint"))
			c.Identity = sp("by_default")
			return c
		}(), "id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL"},
		{"generated stored", func() snapshot.Column {
			c := col("b", "integer")
			c.Generated, c.GenerationExpr = sp("stored"), sp("(a * 2)")
			return c
		}(), "b integer GENERATED ALWAYS AS ((a * 2)) STORED"},
		{"quoted name", col("Odd Name", "text"), `"Odd Name" text`},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			r := render(t, nil, tbl("t", snapshot.Column{Name: "a", TypeName: "integer", Nullable: true}, tc.col))
			if !strings.Contains(r.SQL, tc.want) {
				t.Errorf("want %q in:\n%s", tc.want, r.SQL)
			}
		})
	}
}

// A generation expression is not a default, and PG18 defaults it to VIRTUAL.
// The bundled parser is PG17, so the syntax check has to allow for that without
// changing what is emitted.
func TestRenderVirtualGeneratedColumn(t *testing.T) {
	c := col("b", "integer")
	c.Generated, c.GenerationExpr = sp("virtual"), sp("(a * 2)")

	r := render(t, nil, tbl("t", col("a", "integer"), c))
	if !strings.Contains(r.SQL, "GENERATED ALWAYS AS ((a * 2)) VIRTUAL") {
		t.Errorf("virtual rendered as something else:\n%s", r.SQL)
	}
	if strings.Contains(r.SQL, "STORED") {
		t.Errorf("the parser workaround leaked into the output:\n%s", r.SQL)
	}
}

func TestRenderConstraintsAndIndexes(t *testing.T) {
	tab := tbl("orders", col("id", "bigint"), col("user_id", "bigint"))
	tab.Constraints = []snapshot.Constraint{
		{Name: "orders_pkey", Kind: snapshot.ConstraintPrimaryKey, Definition: sp("PRIMARY KEY (id)")},
		{Name: "orders_total_check", Kind: snapshot.ConstraintCheck, Definition: sp("CHECK (id > 0)")},
		{Name: "orders_user_fkey", Kind: snapshot.ConstraintForeignKey, Definition: sp("FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE")},
	}
	tab.Indexes = []snapshot.Index{
		// the constraint creates this one; emitting it again fails on the name
		{Name: "orders_pkey", IsPrimary: true, Definition: "CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id)"},
		{Name: "orders_user_id_idx", Definition: "CREATE INDEX orders_user_id_idx ON public.orders USING btree (user_id)"},
	}

	r := render(t, nil, tab)
	for _, want := range []string{
		"CONSTRAINT orders_pkey PRIMARY KEY (id)",
		"CONSTRAINT orders_total_check CHECK (id > 0)",
		// after the table, so the referenced table can exist first
		"ALTER TABLE public.orders ADD CONSTRAINT orders_user_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;",
		"CREATE INDEX orders_user_id_idx",
	} {
		if !strings.Contains(r.SQL, want) {
			t.Errorf("missing %q in:\n%s", want, r.SQL)
		}
	}
	if strings.Contains(r.SQL, "CREATE UNIQUE INDEX orders_pkey") {
		t.Errorf("emitted the constraint's own index:\n%s", r.SQL)
	}
	// inside CREATE TABLE it would demand the referenced table already exist
	if strings.Contains(r.Statements[0], "FOREIGN KEY") {
		t.Errorf("foreign key rendered inside CREATE TABLE:\n%s", r.Statements[0])
	}
}

// backs_constraint is absent from older captures, so the shared name has to be
// what the skip goes on.
func TestRenderSkipsConstraintIndexWithoutTheFlag(t *testing.T) {
	tab := tbl("t", col("email", "text"))
	tab.Constraints = []snapshot.Constraint{
		{Name: "t_email_key", Kind: snapshot.ConstraintUnique, Definition: sp("UNIQUE (email)")},
	}
	tab.Indexes = []snapshot.Index{
		{Name: "t_email_key", Definition: "CREATE UNIQUE INDEX t_email_key ON public.t USING btree (email)"},
	}
	if r := render(t, nil, tab); strings.Contains(r.SQL, "CREATE UNIQUE INDEX t_email_key") {
		t.Errorf("would fail on a duplicate relation name:\n%s", r.SQL)
	}
}

func TestRenderPartitionedParent(t *testing.T) {
	tab := tbl("events", col("created_at", "timestamptz"))
	tab.PartitionInfo = &snapshot.PartitionInfo{
		Strategy: snapshot.PartitionRange, Key: "RANGE (created_at)",
		Children: []snapshot.PartitionChild{{Schema: "public", Name: "events_p1", Bound: "FOR VALUES FROM ('2025-01-01') TO ('2025-02-01')"}},
	}
	if r := render(t, nil, tab); !strings.Contains(r.SQL, ") PARTITION BY RANGE (created_at);") {
		t.Errorf("parent lost its partition key:\n%s", r.SQL)
	}
}

// A partition inherits its shape; re-declaring the columns would create a
// standalone table of the same name.
func TestRenderPartitionChild(t *testing.T) {
	parent := tbl("events", col("created_at", "timestamptz"))
	parent.PartitionInfo = &snapshot.PartitionInfo{
		Strategy: snapshot.PartitionRange, Key: "RANGE (created_at)",
		Children: []snapshot.PartitionChild{{Schema: "public", Name: "events_p1", Bound: "FOR VALUES FROM ('2025-01-01') TO ('2025-02-01')"}},
	}
	child := tbl("events_p1", col("created_at", "timestamptz"))
	snap := &snapshot.SchemaSnapshot{Tables: []snapshot.Table{*parent, *child}}

	r := render(t, snap, child)
	want := "CREATE TABLE public.events_p1 PARTITION OF public.events FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');"
	if r.SQL != want {
		t.Errorf("\n got: %s\nwant: %s", r.SQL, want)
	}
}

func TestRenderTableExtras(t *testing.T) {
	tab := tbl("t", col("a", "integer"))
	tab.Reloptions = []string{"fillfactor=70"}
	tab.RLSEnabled = true
	tab.Comment = sp("it's a table")
	tab.Columns[0].Comment = sp("a column")
	tab.Policies = []snapshot.RlsPolicy{{
		Name: "p", Command: "SELECT", Permissive: false,
		Roles: []string{"app_user"}, UsingExpr: sp("(tenant_id = 1)"),
	}}
	tab.Triggers = []snapshot.Trigger{{
		Name: "trg", Definition: "CREATE TRIGGER trg BEFORE INSERT ON public.t FOR EACH ROW EXECUTE FUNCTION touch()",
	}}

	r := render(t, nil, tab)
	for _, want := range []string{
		"WITH (fillfactor=70);",
		"ALTER TABLE public.t ENABLE ROW LEVEL SECURITY;",
		"CREATE POLICY p ON public.t AS RESTRICTIVE FOR SELECT TO app_user USING ((tenant_id = 1));",
		"CREATE TRIGGER trg BEFORE INSERT ON public.t",
		"COMMENT ON TABLE public.t IS 'it''s a table';",
		"COMMENT ON COLUMN public.t.a IS 'a column';",
	} {
		if !strings.Contains(r.SQL, want) {
			t.Errorf("missing %q in:\n%s", want, r.SQL)
		}
	}
	if !containsAny(r.Omitted, "the functions these triggers call") {
		t.Errorf("omitted = %v", r.Omitted)
	}
}

func TestOmitted(t *testing.T) {
	t.Run("always", func(t *testing.T) {
		r := render(t, nil, tbl("t", col("a", "integer")))
		for _, want := range alwaysOmitted {
			if !containsAny(r.Omitted, want) {
				t.Errorf("missing %q in %v", want, r.Omitted)
			}
		}
	})

	// the snapshot records no sequences at all, so a serial column cannot be
	// rebuilt from it
	t.Run("sequences", func(t *testing.T) {
		c := col("id", "integer")
		c.Default = sp("nextval('t_id_seq'::regclass)")
		r := render(t, nil, tbl("t", c))
		if !contains(r.SQL, "CREATE SEQUENCE IF NOT EXISTS t_id_seq;") {
			t.Errorf("the sequence the default reads was not created:\n%s", r.SQL)
		}
		if !contains(r.SQL, "ALTER SEQUENCE t_id_seq OWNED BY public.t.id;") {
			t.Errorf("the sequence was not tied to its column:\n%s", r.SQL)
		}
		if !containsAny(r.Omitted, "the start and increment of the sequences created above") {
			t.Errorf("omitted = %v", r.Omitted)
		}
	})

	t.Run("enum types", func(t *testing.T) {
		snap := &snapshot.SchemaSnapshot{Enums: []snapshot.EnumType{{Schema: "public", Name: "mood", Labels: []string{"ok"}}}}
		r := render(t, snap, tbl("t", col("m", "mood"), col("ms", "mood[]")))
		if !containsAny(r.Omitted, "CREATE TYPE for mood") {
			t.Errorf("omitted = %v", r.Omitted)
		}
	})

	t.Run("nothing conditional", func(t *testing.T) {
		r := render(t, nil, tbl("t", col("a", "integer")))
		if len(r.Omitted) != len(alwaysOmitted) {
			t.Errorf("unconditional entry leaked: %v", r.Omitted)
		}
	})
}

func TestRenderRefusesWhatItCannotBuild(t *testing.T) {
	if _, err := RenderTable(nil, tbl("t")); err == nil {
		t.Error("a table with no columns rendered")
	}
	if _, err := RenderTable(nil, tbl("t", snapshot.Column{Name: "a"})); err == nil {
		t.Error("a column with no type rendered")
	}
	if _, err := RenderTable(nil, nil); err == nil {
		t.Error("nil table rendered")
	}

	// a definition the snapshot carried through unparseable must not be handed
	// back as pasteable ddl
	tab := tbl("t", col("a", "integer"))
	tab.Constraints = []snapshot.Constraint{{Name: "c", Kind: snapshot.ConstraintCheck, Definition: sp("CHECK ((")}}
	if _, err := RenderTable(nil, tab); err == nil {
		t.Error("unparseable ddl was returned")
	}
}

// Every table in the shipped demo snapshot, which is a real capture.
func TestRenderDemoSchema(t *testing.T) {
	data, err := os.ReadFile("../../examples/demo/.dryrun/schema.json")
	if err != nil {
		t.Fatalf("the demo snapshot is committed and is the only real capture under test: %v", err)
	}
	var snap snapshot.SchemaSnapshot
	if err := json.Unmarshal(data, &snap); err != nil {
		t.Fatal(err)
	}
	if len(snap.Tables) == 0 {
		t.Fatal("demo snapshot has no tables")
	}
	for i := range snap.Tables {
		tab := &snap.Tables[i]
		r, err := RenderTable(&snap, tab)
		if err != nil {
			t.Errorf("%s.%s: %v", tab.Schema, tab.Name, err)
			continue
		}
		if !containsPrefix(r.Statements, "CREATE TABLE ") {
			t.Errorf("%s.%s has no CREATE TABLE: %v", tab.Schema, tab.Name, r.Statements)
		}
		if !r.ParseChecked {
			t.Errorf("%s.%s was not syntax-checked", tab.Schema, tab.Name)
		}
	}
}

func contains(hay, needle string) bool { return strings.Contains(hay, needle) }

func containsAny(hay []string, needle string) bool {
	for _, h := range hay {
		if h == needle {
			return true
		}
	}
	return false
}

func containsPrefix(hay []string, prefix string) bool {
	for _, h := range hay {
		if strings.HasPrefix(h, prefix) {
			return true
		}
	}
	return false
}

// A column named "order" is legal in Postgres and unparseable unquoted. Before
// this, one such column denied the whole table its DDL.
func TestRenderQuotesKeywords(t *testing.T) {
	r := render(t, nil, tbl("t", col("order", "text"), col("user", "text"), col("value", "text"), col("email", "text")))
	for _, want := range []string{`"order" text`, `"user" text`} {
		if !contains(r.SQL, want) {
			t.Errorf("reserved keyword left unquoted, want %q in:\n%s", want, r.SQL)
		}
	}
	// unreserved keywords are legal as names, and quoting every one is noise
	for _, want := range []string{"value text", "email text"} {
		if !contains(r.SQL, want) {
			t.Errorf("want %q unquoted in:\n%s", want, r.SQL)
		}
	}
}

// A partition can itself be partitioned. Rendering it as a leaf loses the
// sub-key, and its own children then fail to attach.
func TestRenderNestedPartition(t *testing.T) {
	root := tbl("root", col("a", "integer"), col("b", "integer"))
	root.PartitionInfo = &snapshot.PartitionInfo{
		Strategy: snapshot.PartitionRange, Key: "RANGE (a)",
		Children: []snapshot.PartitionChild{{Schema: "public", Name: "mid", Bound: "FOR VALUES FROM (1) TO (10)"}},
	}
	mid := tbl("mid", col("a", "integer"), col("b", "integer"))
	mid.PartitionInfo = &snapshot.PartitionInfo{
		Strategy: snapshot.PartitionList, Key: "LIST (b)",
		Children: []snapshot.PartitionChild{{Schema: "public", Name: "leaf", Bound: "FOR VALUES IN (1)"}},
	}
	snap := &snapshot.SchemaSnapshot{Tables: []snapshot.Table{*root, *mid}}

	want := "CREATE TABLE public.mid PARTITION OF public.root FOR VALUES FROM (1) TO (10) PARTITION BY LIST (b);"
	if got := render(t, snap, mid).SQL; got != want {
		t.Errorf("\n got: %s\nwant: %s", got, want)
	}
}

// Every partition carries a copy of the parent's constraints and indexes, and
// the snapshot does not record which are local, so re-adding them would fail on
// the name.
func TestRenderPartitionSkipsInheritedObjects(t *testing.T) {
	parent := tbl("events", col("id", "bigint"))
	parent.PartitionInfo = &snapshot.PartitionInfo{
		Strategy: snapshot.PartitionRange, Key: "RANGE (id)",
		Children: []snapshot.PartitionChild{{Schema: "public", Name: "events_p1", Bound: "FOR VALUES FROM (1) TO (10)"}},
	}
	child := tbl("events_p1", col("id", "bigint"))
	child.Constraints = []snapshot.Constraint{
		{Name: "events_ref_fk", Kind: snapshot.ConstraintForeignKey, Definition: sp("FOREIGN KEY (id) REFERENCES ref(id)")},
	}
	child.Indexes = []snapshot.Index{{Name: "events_p1_id_idx", Definition: "CREATE INDEX events_p1_id_idx ON public.events_p1 USING btree (id)"}}

	snap := &snapshot.SchemaSnapshot{Tables: []snapshot.Table{*parent, *child}}
	child.Columns[0].Default = sp("nextval('events_id_seq'::regclass)")
	r := render(t, snap, child)
	if contains(r.SQL, "ADD CONSTRAINT") || contains(r.SQL, "CREATE INDEX") {
		t.Errorf("re-added what the partition inherits:\n%s", r.SQL)
	}
	// re-owning the parent's sequence would drop it with the partition
	if contains(r.SQL, "SEQUENCE") {
		t.Errorf("touched the sequence the parent's default owns:\n%s", r.SQL)
	}
	if !containsAny(r.Omitted, "the parent table, and any constraint or index this partition adds of its own") {
		t.Errorf("omitted = %v", r.Omitted)
	}
}

// pg_get_indexdef writes ON ONLY for an index on a partitioned table; applied
// as-is it never attaches to the partitions and the planner ignores it.
func TestRenderIndexOnPartitionedParent(t *testing.T) {
	tab := tbl("events", col("created_at", "timestamptz"))
	tab.PartitionInfo = &snapshot.PartitionInfo{Strategy: snapshot.PartitionRange, Key: "RANGE (created_at)"}
	tab.Indexes = []snapshot.Index{{
		Name:       "events_created_idx",
		Definition: "CREATE INDEX events_created_idx ON ONLY public.events USING btree (created_at)",
	}}
	r := render(t, nil, tab)
	if contains(r.SQL, "ON ONLY") {
		t.Errorf("index would not attach to the partitions:\n%s", r.SQL)
	}
	if !contains(r.SQL, "CREATE INDEX events_created_idx ON public.events USING btree (created_at);") {
		t.Errorf("index lost:\n%s", r.SQL)
	}
}

// A partition with no recorded bound would otherwise fall through to a
// standalone CREATE TABLE of the same name.
func TestRenderPartitionWithoutABound(t *testing.T) {
	parent := tbl("events", col("id", "bigint"))
	parent.PartitionInfo = &snapshot.PartitionInfo{
		Strategy: snapshot.PartitionRange, Key: "RANGE (id)",
		Children: []snapshot.PartitionChild{{Schema: "public", Name: "events_p1"}},
	}
	child := tbl("events_p1", col("id", "bigint"))
	snap := &snapshot.SchemaSnapshot{Tables: []snapshot.Table{*parent, *child}}

	_, err := RenderTable(snap, child)
	if err == nil {
		t.Fatal("rendered a partition as a standalone table")
	}
	if !contains(err.Error(), "no bound") {
		t.Errorf("error should name the missing bound, got: %v", err)
	}
}

func TestRenderStatisticsTarget(t *testing.T) {
	c := col("a", "integer")
	target := int16(500)
	c.StatisticsTarget = &target
	if r := render(t, nil, tbl("t", c)); !contains(r.SQL, "ALTER TABLE public.t ALTER COLUMN a SET STATISTICS 500;") {
		t.Errorf("statistics target dropped:\n%s", r.SQL)
	}
}

// The strings being checked are mostly Postgres' own deparse output, so on a
// newer server a parse failure means the grammar is old, not the SQL wrong.
func TestParseGateYieldsToANewerServer(t *testing.T) {
	tab := tbl("t", col("a", "integer"))
	tab.Constraints = []snapshot.Constraint{
		{Name: "c", Kind: snapshot.ConstraintPrimaryKey, Definition: sp("PRIMARY KEY (a, valid_at WITHOUT OVERLAPS)")},
	}

	t.Run("newer than the parser", func(t *testing.T) {
		r, err := RenderTable(&snapshot.SchemaSnapshot{PgVersion: "18.3.0", Tables: []snapshot.Table{*tab}}, tab)
		if err != nil {
			t.Fatalf("a pg18 snapshot was denied its ddl: %v", err)
		}
		if r.ParseChecked || r.ParseError == "" {
			t.Errorf("should say it could not check: %+v", r)
		}
	})

	t.Run("same as the parser", func(t *testing.T) {
		if _, err := RenderTable(&snapshot.SchemaSnapshot{PgVersion: "17.2", Tables: []snapshot.Table{*tab}}, tab); err == nil {
			t.Error("unparseable ddl from a pg17 snapshot was returned")
		}
	})
}

func TestMajor(t *testing.T) {
	for _, tc := range []struct {
		in   string
		want int
	}{
		{"18.3.0", 18}, {"PostgreSQL 17.2 on x86_64", 17}, {"16", 16}, {"", 0}, {"nonsense", 0},
	} {
		if got := major(&snapshot.SchemaSnapshot{PgVersion: tc.in}); got != tc.want {
			t.Errorf("major(%q) = %d, want %d", tc.in, got, tc.want)
		}
	}
}

func TestOmittedNamesWhatIsMissing(t *testing.T) {
	tab := tbl("orders", col("user_id", "bigint"))
	tab.Constraints = []snapshot.Constraint{{
		Name: "orders_user_fkey", Kind: snapshot.ConstraintForeignKey,
		FKTable: sp("public.users"), Definition: sp("FOREIGN KEY (user_id) REFERENCES users(id)"),
	}}
	tab.PartitionInfo = &snapshot.PartitionInfo{
		Strategy: snapshot.PartitionRange, Key: "RANGE (user_id)",
		Children: []snapshot.PartitionChild{{Schema: "public", Name: "o1"}, {Schema: "public", Name: "o2"}},
	}
	snap := &snapshot.SchemaSnapshot{Extensions: []snapshot.Extension{{Name: "citext"}}}

	r := render(t, snap, tab)
	for _, want := range []string{
		"the tables these foreign keys point at: public.users",
		"2 partitions of this table, each its own CREATE TABLE",
		"CREATE EXTENSION for anything these types or operators come from",
	} {
		if !containsAny(r.Omitted, want) {
			t.Errorf("missing %q in %v", want, r.Omitted)
		}
	}
}

// The order is the contract for anything diffing statement by statement.
func TestStatementOrder(t *testing.T) {
	tab := tbl("t", col("a", "integer"))
	tab.Comment = sp("c")
	tab.Constraints = []snapshot.Constraint{
		{Name: "fk", Kind: snapshot.ConstraintForeignKey, Definition: sp("FOREIGN KEY (a) REFERENCES u(b)")},
	}
	tab.Indexes = []snapshot.Index{{Name: "i", Definition: "CREATE INDEX i ON public.t USING btree (a)"}}

	got := render(t, nil, tab).Statements
	want := []string{"CREATE TABLE ", "ALTER TABLE public.t ADD CONSTRAINT fk", "CREATE INDEX i", "COMMENT ON TABLE"}
	if len(got) != len(want) {
		t.Fatalf("got %d statements, want %d: %v", len(got), len(want), got)
	}
	for i := range want {
		if !strings.HasPrefix(got[i], want[i]) {
			t.Errorf("statement %d = %q, want prefix %q", i, got[i], want[i])
		}
	}
}
